# Generated by Django 4.2.16 on 2026-06-26 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(help_text='e.g. user:<id>, listing:<id>', max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ttl_days', models.PositiveSmallIntegerField(default=7)),
                ('offer_default_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('fuzz_radius_m', models.PositiveSmallIntegerField(default=400)),
                ('auto_hide_reports', models.PositiveSmallIntegerField(default=3)),
                ('max_listings_per_day', models.PositiveSmallIntegerField(default=10)),
                ('max_claims_per_day', models.PositiveSmallIntegerField(default=30)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform configuration',
            },
        ),
    ]
